### ISSUE TITLE
src/leveldb/libleveldb.a: No such file or directory

### ISSUE THREAD

**Issue by ezzyftw** [davorcc/DavorCoin#1]
Some people will encounter the error:

src/leveldb/libleveldb.a: No such file or directory
/src/leveldb/libmemenv.a: No such file or directory
when compiling do the following:

cd DavorCoin/src/leveldb
chmod 755 *
cd 
and compile again

**Comment by davorcc** [comment]
Dear ezzyftw,

Thanks for helping troubleshooting the compiling progress, you contribution is appreciated!

Best regards,
