### ISSUE TITLE
 blkindex.dat

### ISSUE THREAD

**Issue by Mustyphil** [davorcc/DavorCoin#4]
I am having error loading blkindex.dat while trying to open my desktop wallet. please what is wrong

**Comment by davorcc** [comment]
Hi Mustyphil,

This means the blockchain data is corrupted. If you are using Windows, please go to %APPDATA%\DavorCoin and delete all the files and folders inside EXCEPT wallet.dat (if you delete wallet.dat, all your coins will disappeared). Then restart the DavorCoin-Qt, the blockchain will be synced from scratch. After that you can start using the wallet.

Best regards,

**Comment by Mustyphil** [comment]
Thanks DONE.
