### ISSUE TITLE
Davor coin login issue

### ISSUE THREAD

**Issue by vips2000ranker** [davorcc/DavorCoin#6]
I tried a lot to login my acount after lending money and they continuously shows that your account is temporary locked. And when I contacted support, they replied that your account is associated with suspiciously earning of affiliated bonus. 
Oh come on guys, dont pull your reputation down.
I can earn affiliate bonus if I have downline person and you can check my account. There is no any downline. So, dont be childish and unlock my account.

**Comment by davorcc** [comment]
Dear Patel,

The system detects your multiple accounts by checking all your related info not just your downlines. Please contact support and ask them to give you your detailed information.

Best regards,

**Comment by vips2000ranker** [comment]
Hello,
     I tried multiple times to contact support team about my issue but each time they just replies the copy and paste formate about multiple account. One thing I want to clear that I am the genuine invester on your lending platform and if multiple account found about my upline then its not my fault. You have to lock the multiple account of my upline. Why you lock my account as I didnt get any single penny as affiliate bonus as I am the invester? 
So, stop harrassing the genuine investers and unlock my account and upgrade your support team to read the issue carefully inplace of just copy and paste the predecided formate.

**Comment by vips2000ranker** [comment]
Hello,
I tried multiple times to contact support team about my issue but each time
they just replies the copy and paste formate about multiple account. One
thing I want to clear that I am the genuine invester on your lending
platform and if multiple account found about my upline then its not my
fault. You have to lock the multiple account of my upline. Why you lock my
account as I didnt get any single penny as affiliate bonus as I am the
invester?
So, stop harrassing the genuine investers and unlock my account and upgrade
your support team to read the issue carefully inplace of just copy and
paste the predecided formate.

And still you think that its my fault to be genuine investers then deduct
the affiliate bonus you gave to my upline from my lending amount as I
lended 34000 USD and I pretty sure that you never gave such huge amount to
my upline as affiliate bonus. So, stop harrassing me and unlock my account.
